-- Provisio / Freshline — close the email-enumeration hole resolve_login_email
-- (0018) still had on its own, separate from the 3-attempt lockout (0044).
--
-- resolve_login_email(p_login) was grant execute to anon so the login flow
-- could look an email up *before* having a session — but that grant let
-- anyone call it directly (not through the login edge function) and tell,
-- from the response alone, whether a login/email exists: a match returns
-- the account's real email, no match echoes the input back unchanged. Going
-- through the actual login edge function never leaked this (a bad password
-- and a nonexistent login both come back as the same generic "Неверный
-- логин или пароль"), and the app already exclusively signs in through that
-- function (see "Security: route sign-in through the login Edge Function") —
-- nothing legitimate ever called this RPC directly. Same treatment as
-- check_login_lock/record_login_result in 0048: service_role-only now, the
-- edge function's existing service-role client makes the call instead.
--
-- Unlike 0044 (which 0048 built on), 0018 never revoked the implicit
-- default PUBLIC execute grant every new function gets — it only added an
-- explicit grant to anon/authenticated on top of it. Revoking just from
-- anon/authenticated therefore did nothing on its own; PUBLIC (which every
-- role, including anon, inherits through) still let anyone call it. Caught
-- live by testing a direct anon RPC call after this migration first shipped
-- without the "from public" revoke below — it still succeeded.
revoke all on function public.resolve_login_email(text) from public;
grant execute on function public.resolve_login_email(text) to service_role;
